export const STAGE_WIDTH_TILES = 35;
export const STAGE_HEIGHT_TILES = 20;
export const TILE_SIZE = 16;

export const ACTIVITY_PLAY = "ACTIVITY_PLAY";
export const ACTIVITY_SELECT_LEVEL = "ACTIVITY_SELECT_LEVEL";

export const MODAL_RELEASE_NOTES = "MODAL_RELEASE_NOTES";
